services:
  request-server:
    build:
      context: ./request-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-webflux-sample-nw
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  spring-webflux-sample-nw:
    driver: bridge
