services:
  call-api-app:
    build:
      context: ./call-api-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-non-blocking-api-call-sample-nw
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - request-server
    environment:
      APP_REQUEST_SERVER_DOMAIN: host.docker.internal

  request-server:
    build:
      context: ./request-server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - spring-non-blocking-api-call-sample-nw
    healthcheck:
      test: "curl -f http://localhost:8081/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  spring-non-blocking-api-call-sample-nw:
    driver: bridge
